package org.apache.servicemix.samples.wsdl_first;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.0.redhat-610379
 * 2016-09-27T14:09:38.405+02:00
 * Generated source version: 2.7.0.redhat-610379
 * 
 */
@WebServiceClient(name = "PersonService", 
                  wsdlLocation = "file:/C:/redhat%20fuse%208/cxf-basic/src/main/resources/wsdl/person.wsdl",
                  targetNamespace = "http://servicemix.apache.org/samples/wsdl-first") 
public class PersonService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicemix.apache.org/samples/wsdl-first", "PersonService");
    public final static QName Soap = new QName("http://servicemix.apache.org/samples/wsdl-first", "soap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/redhat%20fuse%208/cxf-basic/src/main/resources/wsdl/person.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PersonService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/redhat%20fuse%208/cxf-basic/src/main/resources/wsdl/person.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PersonService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PersonService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PersonService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Person
     */
    @WebEndpoint(name = "soap")
    public Person getSoap() {
        return super.getPort(Soap, Person.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Person
     */
    @WebEndpoint(name = "soap")
    public Person getSoap(WebServiceFeature... features) {
        return super.getPort(Soap, Person.class, features);
    }

}
